### ISSUE TITLE
Force graph example not working: `Could not convert to correct data type`

### ISSUE THREAD

**Issue by brianbreitsch** [lightning-viz/lightning-python#16]
I'm running IPython (3.0) notebook and Python 3.4.

The Force graph example:

```Python
import networkx as nx
from numpy import random

G = nx.random_regular_graph(3,100)
mat = nx.adjacency_matrix(G).todense()
l = (random.rand(100)*5).astype('int')

lgn.force(mat, label=l)
```

Is producing the following error, and no graph is created.

```Python
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-30-5899ada8ac48> in <module>()
      6 l = (random.rand(100)*5).astype('int')
      7 
----> 8 lgn.force(mat, label=l)

<string> in <lambda>(self, matrix, color, label, size)

/home/breitsbw/anaconda3/lib/python3.4/site-packages/lightning/types/decorators.py in plotter(self, *args, **kwargs)
     11         if not hasattr(self, 'session'):
     12             self.create_session()
---> 13         viz = VizType.baseplot(self.session, VizType._name, *args, **kwargs)
     14         self.session.visualizations.append(viz)
     15         return viz

/home/breitsbw/anaconda3/lib/python3.4/site-packages/lightning/types/base.py in baseplot(cls, session, type, *args, **kwargs)
    104             raise Exception("Must provide a plot type")
    105 
--> 106         data = cls.clean_data(*args, **kwargs)
    107 
    108         if 'images' in data and len(data) > 1:

/home/breitsbw/anaconda3/lib/python3.4/site-packages/lightning/types/base.py in clean_data(cls, *args, **kwargs)
     79                     data[key] = datadict[key]
     80                 else:
---> 81                     d = cls.ensure_dict_or_list(datadict[key])
     82                     data[key] = cls.check_unkeyed_arrays(key, d)
     83 

/home/breitsbw/anaconda3/lib/python3.4/site-packages/lightning/types/base.py in ensure_dict_or_list(x)
     53 
     54         # add other data type conversions here
---> 55         raise Exception("Could not convert to correct data type")
     56 
     57     @classmethod

Exception: Could not convert to correct data type
```

I tried all sorts of combinations of `.astype(int)` and `asarray`, as well as omitting the `label` argument.

**Comment by brianbreitsch** [comment]
I figured out that a Python `range` was being passed into `ensure_dict_or_list` and was able to get it to work by adding

```Python
if isinstance(x, range):
    return list(x)
```

I still don't know what the range is or where it came from--I will investigate now.

**Comment by brianbreitsch** [comment]
The `range` was `range(0, 100)`.

**Comment by brianbreitsch** [comment]
The culprit is in `plots.py`:

`nodes = range(0, matrix.shape[0])`

Was the idea to have uniform ranges be jsonable and passed to the server?--because I think that would actually be really smart.

**Comment by freeman-lab** [comment]
Nice @brianbreitsch ! Thanks for reporting, and great digging into it. This is a Python 2 -> 3 issue, in 3.x `range` has replaced `xrange` and no longer produces a list.

The simplest fix would just be to cast the range as a list, via:

```
nodes = list(range(0, matrix.shape[0]))
```

If we check for `range` as in your suggestion, it would fix 3.x but cause an error in 2.x because `range` is not a type, though we could work around that with a `try` or something. And I agree it would be nice to handle the general case. Want to take a stab at a PR?

**Comment by brianbreitsch** [comment]
I've never made a pull request before, but I'd love to give it a try!
I can implement that simple fix that you suggest above.

**Comment by freeman-lab** [comment]
Ok great! Yeah let's start with the simple fix. The basic workflow is to fork the repo, make a branch, commit the change, then go view your branch on github and create the PR. There are some good walkthroughs online, I like [this](https://gun.io/blog/how-to-github-fork-branch-and-pull-request/) one.
