### ISSUE TITLE
Plots are not shown.

### ISSUE THREAD

**Issue by dav009** [lightning-viz/lightning-python#8]
Im trying a fairly simple script to plot a line from python.
The session is created, there is no exception being thrown
however when I go to the session no plots are created.
Here is my code:

```
l = Lightning(host="http://localhost:3000")
l.create_session("line")
l.plot(data=[1,2,3], type="line")
```

If I go to the webinterface I am able to create a plot and it actually shows alright.

**Comment by mathisonian** [comment]
Hey @dav009,

Sorry the docs in the README were a little outdated. I've updated, and the most up-to-date docs are also here: http://lightning-viz.org/lightning-python/

You can shorten your code to:
```
l = Lightning(host="http://localhost:3000")
l.create_session("line")
l.line([1,2,3])
```

**Comment by freeman-lab** [comment]
Also, FYI, the following does work:

```
l.plot(data={"series": [1,2,3]}, type="line")
```

The `plot` method is a generic plotter that will let you generate any plot type (including a custom one), but does no parsing or formatting of the input. It will pass the dictionary along directly to the plot. So it will work fine if the dictionary is in the correct format (e.g. `{"series": [1,2,3]}` for the default `line` chart).

This is mainly useful for generating custom visualizations for which there is not (yet) an associated method in the official client.

Will expand the documentation to explain this!

**Comment by dav009** [comment]
awesome! thanks for the quick support
